### PR TITLE
Created a barebones implementation of the itinerary page

### PR DESCRIPTION
**Pull request by tylereg03**
Added the files ItineraryAccordion.js and ItineraryPage.js.

In ItineraryPage.js, we can:

Created the ability to click into days using a MUI accordion component.
Created the ability to click into specific activities using a MUI accordion component.
Add activities within each individual day.
Edit activities within each individual day.
Remove activities within each individual day.
Add additional days.
Confirm removal of activities with a MUI dialog popup.

TODO:

Be able to remove days.
Make the prompt for adding activities include start times, and end times.
Turn the prompt for editing activities into a new MUI dialog popup.
Be able to dynamically place new activities sequentially according to their time slots.
Make the itinerary page look more professional.

### CODE REVIEW

**Review by renm10 — APPROVED** [review]
Everything looks great, very good starting point. Tried listed functions and everything works as intended.

**Comment by axelauda** [comment]
All functioned mentioned in the commit working as intended. A solid foundation for the itinerary page that we can work off of. Approved!!

**Review by axelauda — COMMENTED** [review]
All functioned mentioned in the commit working as intended. A solid foundation for the itinerary page that we can work off of. Approved!!

**Review by axelauda — APPROVED** [review]
Sorry, here's my actual approval.

**Pull request merged**
