### PR TITLE
Added MapPage.css and Editted MapPage.js

### PR DESCRIPTION
**Pull request by printer99**
+ Added a search bar and continent list
+ Enlarged the map and gave it a black border
+ Styled it a little with css

- Will add functionality on buttons and search bar in the future

### CODE REVIEW

**Review by Niblick1020 — APPROVED** [review]
This update introduces a dynamic continent list feature to the MapPage, enhancing interactivity and user engagement. The integration of React useState for visibility toggling and event handlers for mouse actions significantly improves the UX. Great job on implementing a clean and responsive design, especially with the smooth transition effects for the continent list.

**Review by VyProductions — CHANGES_REQUESTED** [review]
Tested the page layout on my end. I think the map size is perfect, as it leaves some space on the side for other elements if we were to add them, however it doesn't scale appropriately when the website is oriented vertically (similar to mobile).

I'd also think that having the hot spot component be positioned below the navigation bar would look better, as currently it forces the sign in / user profile area of the navigation bar to have arbitrary white-space to its right so they don't intersect when the component slides out.

Before approving this I'd request that these changes are made:
1. Look into a solution for vertical resolution display.
2. Adjust the vertical position of the hot spot list so that it doesn't overlap with the navigation bar.
3. Possibly move the sign-in / user profile to get rid of the right-most whitespace.

This is an example of what I mean by the 3rd condition:

image

**Comment by printer99** [comment]
I have changed the map so that it changes to percentage of the screen based on screen size.

**Review by VyProductions — APPROVED** [review]
Just tested the map scaling and it appears to work correctly. I'd still request that you take a look into adjusting the vertical location and vertical scaling of the hotspot list. It doesn't seem like you touched it at all after my original review.

For now I'll approve this change so we can move forward.

**Pull request merged**
