### PR TITLE
Hot fix for theme toggle error and log in button gone in mobile view

### LINKED ISSUE #84: Theme Toggle not working
**Describe the bug**
The theme toggle button is now not working anymore, there is no animation for it and when click it, it does nothing

**To Reproduce**
1. Go to any page
2. On the top right corner, click on toggle button

**Expected behavior**
It should switch between default light and dark theme

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
One of the new merges possibly could cause this issue. Especially if it is modify anything for the navBar

### PR DESCRIPTION
**Pull request by jenlcmc**
# Description

This pull request introduces several improvements to enhance the application's user interface and security aspects. The fundamental changes include fixing the theme toggle button that did not work before and log in button not show up in mobile view, updating the password fields to hide the password by default (type `password`), and adding a toggle icon button for password visibility. This allows users to toggle the visibility of their password for ease of use.

Fixes #84 and #96

# Add an image of the change (if applicable)

Screenshot 2024-04-01 at 1 43 46 PM
Screenshot 2024-04-01 at 1 43 49 PM

# Type of change

- [x] Bug fix (fixes theme toggle button)
- [x] New feature (adds password visibility toggle)
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by esquek1 — CHANGES_REQUESTED** [review]
I tested the website and looks great from an un-signed-account. If the second reviewer can test through a signed account, I think we can approve of this fix. However, there is a minor conflict regarding App.js. When you resolve this, I can approve. 

I also noticed this issue, however it is not related to the theme toggle. GettingStarted Page banner needs to be relative, and sign in button goes missing when page is too zoomed in.
image

**Comment by jenlcmc** [comment]
No log in button is related to issue #96

**Comment by jenlcmc** [comment]
The reponsive scalling will be fix later as it is not priority right now

**Review by esquek1 — APPROVED** [review]
I see you've fixed the merging conflict. Approved!

**Review by amai83 — APPROVED** [review]
Reviewed code, noticed that formatting was cleaned up. Everything is working properly, bugs were fixed, overall adding improved functionality to the website. Added extra toggle feature to view password as well. Approved.

**Pull request merged**
