### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by Jordan-Scherf**
Created the issues template for Bug Issues and Feature Enhancements. This allows everyone to be more descriptive with Bug reports as well as Feature Enhancements.

### CODE REVIEW

**Review by VyProductions — CHANGES_REQUESTED** [review]
Thank you for creating these templates. We might also want one for documentation.

**Review by amai83 — APPROVED** [review]
Bug report template for whenever issues are raised. Template will pull up automatically when an issue is submitted. Approved.

**Review by Ramirez-Christopher — APPROVED** [review]
This is amazing. good issue template.

**Review by printer99 — APPROVED** [review]
Perfect!

**Review by renm10 — APPROVED** [review]
Everything looks fine, nicely formatted template for us to follow when creating an issue.

**Pull request merged**
