### PR TITLE
Added more interface implementations for User, Profile, and Trip model, and fixed sign in issue on back end.

### LINKED ISSUE #104: Authentication Module is Non-Functional during Sign In
**Describe the bug**
When attempting sign-in for an existing account, the website fails to recognize existing user credentials.

**To Reproduce**
1. Go to 'Sign In' dialog
2. Enter valid credentials
3. Click submit
4. See "user does not exist", or similar error message on dialog screen

**Expected behavior**
Correct credentials should produce a valid login session.

### PR DESCRIPTION
**Pull request by VyProductions**
# Description

Implemented more business logic functions for User, Profile, and Trip models. This further addresses #54, and fixes #104.

# Type of change

- [X] Bug fix 
- [X] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by axelauda — COMMENTED** [review]
image

Whenever I tidy the backend and try running main.go, I'm getting the above error and it won't start? I'm not sure if this is just me or not.

**Comment by VyProductions** [comment]
Should be fixed now. Thank you, @axelauda.

**Review by axelauda — APPROVED** [review]
Okay I tested and everything looks to be working correctly. Great job finishing the handlers for the User, Profile, and Trip collections, now we can use those handlers to get information from the database to the front end and properly display information such as displaying the user's username on the Profile Page, or getting the Friends List of current user for the Friends page. We can also now properly sign in with an account, which can be used to blank out certain pages and only display content if the user is properly logged in. Mega Approved!!

**Review by Niblick1020 — APPROVED** [review]
I've conducted tests using a new user account named 'temp' and confirmed the sign-up and sign-out functionalities are operating as expected. The fix appears successful, and I've encountered no further issues while navigating the website. This pull request has my approval for merge. Great work on addressing the problem—thanks for the resolution!

**Pull request merged**
