### PR TITLE
overhaul the UI for expense into expense dashboard

### LINKED ISSUE #44: Adding and redo the UI for expense split as well as integrate the back end
---
name: Feature Development/Enhancement
about: Suggest an improvement/enhancement
title: 'Enhance UI and Functionality for Expense Management Features'
labels: enhancement
assignees: 'jenlcmc'

---

**Is your feature request related to a problem? Please describe.**
Yes, the current UI and functionality for managing expenses, including adding, editing, and viewing detailed expenses, lack coherence and intuitiveness. Users find it cumbersome to navigate through the different aspects of expense management, which affects their overall experience with the application.

**Describe the solution you'd like**
I propose a series of enhancements to the UI and functionality of the expense management features that I will do to improve the UI
- ........ (more to come)
- Redesign the UI to include two tabs in the "Add Expense" dialog, improving the organization of the interface.
- Introduce three tabs within the "Detail Expense" popup, making the breakdown of expenses more accessible.
- Enable the "Detail Dialog" to support both edit and create operations seamlessly.
- Implement an "Expense Split Detail" popup, allowing users to enter detailed information for splitting expenses more effectively.
- Introduce a "Split Method" feature with options for equal and specific costs, providing flexibility in how expenses are divided.
- Revise the "Add Person" dialog to correct the logic of adding rows and include a search feature for the trip list, enhancing user interaction and efficiency.
- Add an "Image Card Matrix" in the "TripsList" component with a dropdown menu for selecting current and past trips, alongside an improved expense split UI.
- Redesign the "Trip List" into a dropdown menu that categorizes trips into current and past, coupled with a grid display of images for a visually engaging overview.
- Incorporate a feature to add random generated people for testing and refine the code for the expense split dialog, ensuring the "Add Person" functionality works as intended.
- Standardize the UI style across the "Expense Split" and "Expense Form" to maintain consistency and improve the visual appeal.

**Describe alternatives you've considered**
- something like wanderlog

**Additional context**
This suite of enhancements aims to significantly improve the user experience for managing expenses within the application, making it more intuitive, visually appealing, and efficient. The proposed changes are based on analyzing current pain points in the expense management process.

### PR DESCRIPTION
**Pull request by jenlcmc**
---
name: "Overhaul the UI for expense split and create expense 2.0 version"
about: "This will overhaul and change the expense split due to logic being confusing when split into multiple tabs and fix small date bug. This also introduce an expense dashboard in which everything will be in same page for faster adding and seeing"
title: "feat: Comprehensive Enhancements to Expense Management UI and Functionality"
labels: "enhancement"
assignees:  @jenlcmc 

---

# Description

This pull request introduces a series of enhancements to the expense management features within our application, focusing on improving both the user interface (UI) and the underlying functionality. Significant changes include:

- Redo UI for the expense page
--  Tab views in add new expense and move the expense split into this form area
- Remove the old UI in which there are 2 tabs on the expense page, as this causes the logic to be confusing
- Add options to split with which are by half or a specific amount
- Adding options to edit existing expense 
- Fix the date error that is always empty
- Clean up the code to remove all non-use code
- Add description field into expense
- Fix code in which it break when it is empty for input fields

These changes aim to significantly improve the user experience of managing expenses, making the process more intuitive, efficient, and visually appealing.

For the expense 2.0 dashboard, I will introduce a new way to manage expenses in which everything will now be on the same page. There will be an overview, expense split, expense activity that shows different categories, and expense history transactions.
- Add Expense split: handle adding new expenses depending on categories to split with someone in same group
- Overview: Show an overview total amount of money (total spend, total owned, and total payback)
- Expense activity: Show all transactions in different categories
- History: Show transactions history 

# The new expense 2.0 dashboard will replace the old UI so I will also remove the old UI 

Fixes #44  and #112

# Add an image of the change (if applicable)
Screenshot 2024-04-10 at 3 33 40 PM

# Type of change

- [x] Bug fix 
- [x] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by FPSwitch — COMMENTED** [review]
This change is a good approach to adjusting the UI. I also saw that you reduced overhead by removing the necessary width and height edits in the TripList.js and making it more universal. If you can also show some screenshots for the specific changes that would help everyone else visualize the changes better.

**Comment by jenlcmc** [comment]
No log in button is related to issue #96

**Review by amai83 — APPROVED** [review]
Tested out the new page for expenses. I really like the layout everything and how it's organized. Some of the containers are off on my screen, but that can be edited when CSS is implemented. I think the activity section is a little too busy, and contains a bit too MUCH details. Will address later. Other than that, the code is clean and well formatted.

**Review by axelauda — APPROVED** [review]
After testing it out, I really like how organized this expenses dashboard makes everything! I do like how you can label everything by category, and are able to see who paid you or who you paid in the Activities panel. The History panel is also great to keep track of past expenses, and filtering by person is helpful to keep track of who owes what. I do think that this dashboard is mainly helpful for larger groups though, and smaller groups might have a harder time using this system effectively or not at all. In that case it might be nice to have both this dashboard and your previous iteration of the expenses page list, which would be a simpler format for those smaller groups. Also having what expenses that you owe specifically at the top would be great since those would likely be the most important for the user to see. Great job, approved!!

**Comment by jenlcmc** [comment]
> After testing it out, I really like how organized this expenses dashboard makes everything! I do like how you can label everything by category, and are able to see who paid you or who you paid in the Activities panel. The History panel is also great to keep track of past expenses, and filtering by person is helpful to keep track of who owes what. I do think that this dashboard is mainly helpful for larger groups though, and smaller groups might have a harder time using this system effectively or not at all. In that case it might be nice to have both this dashboard and your previous iteration of the expenses page list, which would be a simpler format for those smaller groups. Also having what expenses that you owe specifically at the top would be great since those would likely be the most important for the user to see. Great job, approved!!

Thank you @axelauda. I will apply this suggestion to the new merge request. For now, I will just let the dashboard show up first, and the old UI will be hidden if I do not meet the deadline.  If I manage to sync the data, then we are good to use it and we might need to talk with the group to see whether they like this approach or not.

**Pull request merged**
