### PR TITLE
Customization for the Profile Page

### PR DESCRIPTION
**Pull request by axelauda**
Added the following features to the Profile Page:
- Uploading a banner image
- Pick from a collection of default profile pictures as well as import their own custom pictures, where the page remembers the last three custom pictures
- A nametag that will hold a user's username and extend to the number of letters
- Zooming will keep the proportions of the elements of the profile box (still need to adjust some of the other components)
- Organized images into a single folder, which we can use to hold all images on the website

Still need to implement the following features:
- Fill out the structure and implementation of the Profile Tabs
- Figure out how to store user images into the Mongo database
- Restrict the size and format of uploadable images

### CODE REVIEW

**Review by jenlcmc — APPROVED** [review]
- I notice that once I login successful, it seem that the log in button is still there next to the profile button. This will be ref to bug issue #8.
- Also, I think if we add like edit button in the corner for banner and profile pic, it will be easier for users to know that they can edit the pic 
- Option to edit the user name will be good too 
- This is optional but I we could implement page for user to preview the pic and manually adjust it, it good too but seem like it will be a lot of work 
Overall, all changes look good and it work great

**Comment by axelauda** [comment]
> * I notice that once I login successful, it seem that the log in button is still there next to the profile button. This will be ref to bug issue [Remove sign in option when user already signed in & profile status emoji now showing up in the small screens #8](https://github.com/UNLV-CS472-672/2024-S-GROUP6-RW/issues/8).
> * Also, I think if we add like edit button in the corner for banner and profile pic, it will be easier for users to know that they can edit the pic
> * Option to edit the user name will be good too
> * This is optional but I we could implement page for user to preview the pic and manually adjust it, it good too but seem like it will be a lot of work
>   Overall, all changes look good and it work great

**Comment by axelauda** [comment]
@jenlcmc Thank you for the comment! I wasn't sure if editing the username would be something they would do in the profile page or in the settings page where they would also be able to change their password. Also I think that being able to preview the picture would be more of quality of life feature that I could add later on after we have all the required features of the website.

**Review by renm10 — APPROVED** [review]
The customization of the profile page looks amazing! I love how the banner, avatar and the profile picture can all be edited!
However I also do think that we can add like a plus button on the banner or something that shows that the banner is customizable too. To make it even more customizable, I think being able to customize where the username is listed would be awesome too

**Review by tylereg03 — APPROVED** [review]
After looking over the profile page, everything is looking good! The customization options are working as intended, and the overall profile page is much more fun and interactive. This is an excellent improvement to the original profile page. Approved!

**Pull request merged**
