### PR TITLE
Activity display to timeline view

### LINKED ISSUE #100: Change the display of activities into a timeline view
**Is your feature request related to a problem? Please describe.**
Upon adding a edit view to the activity page, the draggability doesn't need to happen here. Therefore, I am moving the draggable feature into the edit view and instead view each activity in a timeline.

**Describe the solution you'd like**
When they click on the itinerary section of each page, they will be presented with a timeline view of each activity where the start time is listed on the left side and the title of each activity on the right side.

**Describe alternatives you've considered**
There isn't any alternative design I've considered yet.

**Additional context**
itinerary_timeline_view

### PR DESCRIPTION
**Pull request by renm10**
# Description

The activities listed on the itinerary page did not have a sense of time, thus adding a timeline view allows users to easily understand their schedule of the day. 

Fixes #100 

# Add an image of the change (if applicable)

right-way-timeline-view

# Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by esquek1 — CHANGES_REQUESTED** [review]
This looks like a great update to the Itinerary Page. In the next PR, user should have the ability to change/add a time when they add an activity. Also, you pushed the package-lock.json by accident. Fix this conflict and I can approve of this PR.
Screenshot from 2024-04-10 15-19-57

**Review by amai83 — APPROVED** [review]
Timeline view is a cleaner and easier way for users to view their itinerary. It is organized chronologically and has a functioning button to add more activities. Overall, a good addition to the application. Approved

**Comment by renm10** [comment]
@esquek1 Thank you for noticing that, I fixed the package-lock.json error, it should have no merge conflicts!

**Review by esquek1 — APPROVED** [review]
The conflict has been resolved. Approved!

**Pull request merged**
