### PR TITLE
Implemented Enhancements to Getting Started Page

### LINKED ISSUE #36: Enhance Homepage for Better Engagement
The homepage lacks visual appeal to capture and retain a users attention effectively. 

Potential solutions:
- Color Scheme / Typography
- Responsive components
- Visual elements

### PR DESCRIPTION
**Pull request by esquek1**
---
name: "Implemented Enhancements to Getting Started Page"
about: "Request a feature"
title: "feat: Interaction with images and animations"
labels: "feature-request, not-reviewed"
assignees: ""
---

# Description

To enhance the homepage for better engagement with users, implemented an image slider to the homepage banner and animations (from LottieFiles) that syncs with scroll/cursor movement.

Resolves #36 

# Add an image of the change (if applicable)
image
image2

# Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by tylereg03 — CHANGES_REQUESTED** [review]
The slider on the getting started page looks great! However, on some of the pictures, the text becomes very difficult to read. Also, on our about us section, again, the legibility of the text is pretty difficult to read. Perhaps there is a way to add a black border around the text that way it becomes easier to read? Once the text becomes easier, I think this is a great pull request.

**Comment by esquek1** [comment]
> The slider on the getting started page looks great! However, on some of the pictures, the text becomes very difficult to read. Also, on our about us section, again, the legibility of the text is pretty difficult to read. Perhaps there is a way to add a black border around the text that way it becomes easier to read? Once the text becomes easier, I think this is a great pull request.

Blurred the bottom image a little bit to make text pop out more, and fixed some things for the banner. 

Screenshot from 2024-03-24 19-29-28
Screenshot from 2024-03-24 19-31-39

**Review by tylereg03 — APPROVED** [review]
This looks a lot better! The text is much more readable, and I think the getting started page looks much more professional. Approved!

**Review by VyProductions — APPROVED** [review]
These changes make the website much more vibrant and eye-catching. I agree that the original version had some readability issues with the foreground text on a few of the images. The blur effect on the background image does help mitigate this issue, but I think a subtle outline / stroke on the font could be a better solution.

We can discuss this with the rest of the group to see if anyone has other feedback. Great work!

**Pull request merged**
