### PR TITLE
Added unit Testing for SignInDialog.js

### PR DESCRIPTION
**Pull request by Niblick1020**
# Description
Added test coverage for SignInDialog.js

# Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by axelauda — APPROVED** [review]
More unit tests are awesome, great job approved!!

**Review by Ramirez-Christopher — APPROVED** [review]
accepted ! thank you for doing unit testing.

**Review by VyProductions — APPROVED** [review]
Thank you for creating tests for the sign in dialog. All for the benefit of our code coverage.

**Review by amai83 — APPROVED** [review]
This pull request contains a unit test for signindialog. It contributes to improving overall coverage. Approved

**Comment by Niblick1020** [comment]
Wow you guys love me

**Review by axelauda — APPROVED** [review]
Just want to reiterate how important this is. Mega approved!!

**Review by renm10 — COMMENTED** [review]
Thank you for the unit testing! Approved

**Pull request merged**
