### PR TITLE
Changed date format on days, fixed dark mode bugs

### LINKED ISSUE #46: Changing format of each day from "Day 1" to "Friday, March 22, 2024".
**Is your feature request related to a problem? Please describe.**
When creating the trip using the date picker, the days are displayed in sequential order rather than showing the dates. This ends up looking sloppy and unreadable, as from a user standpoint, it would be more desirable to see all of your activities planned for a certain day labeled by the appropriate date, rather than "Day 3."

**Describe the solution you'd like**
According to the user input, it would be desirable for each day to be listed in a more readable date format.

- Omit each prefix "day"
- Keep track of the current day (first, second, third, etc.) in order to be able to add more or less days without issue.
- Instead of the current day being displayed as a number, we can instead display it in a "Day of the week, Month Day, Year" format.
- An example of this would be "Friday, March 22, 2024"

**Describe alternatives you've considered**
Instead of the date being formatted like "Friday, March 22, 2024," we can simply use the format "3/22/2024," which may be easier to work with arithmetically.

**Additional context**
Overall, this change will make the itinerary page look much more professional, and will make the user experience more pleasurable. The user will be able to affix their activities to individual dates, rather than having to find out what day your activity is on according to how far into the trip you're into.

### LINKED ISSUE #47: Fixing draggable components appearance in dark mode.
**Describe the bug**
Currently, each draggable component displays properly on light mode. However, when switching to dark mode, each component displays as a solid white rectangle with no information visible. This is obviously a problem for those who wish to use dark mode. 

**To Reproduce**
1. Go to the itinerary page.
2. Click on the sun icon to turn the page into dark mode.
3. Create a trip by inputting two dates.
4. Click on any day, and observe how each activity is a solid white rectangle.

**Expected behavior**
We expect each draggable component to display an activity, regardless of whether the page is in light or dark mode.

**Screenshots**
image

image

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Opera GX]
 - Version [e.g. 107]

**Additional context**
This problem overall greatly decreases the usability of the itinerary page. With fixing the visibility of activities in dark mode, this should allow users to correctly organize their trip.

### PR DESCRIPTION
**Pull request by tylereg03**
---
name: "Date format change"
about: "This change allows the dates to display correctly when inputted by the user, along with being able to add more days with the correct date still showing"
title: "feat: Comprehensive Enhancements to Itinerary UI and Functionality"
labels: "enhancement, bug"
assignees: "@tylereg03"
---

# Description

This pull request makes some QOL changes to the itinerary page, along with fixing some bugs that occurred specifically when the page was in dark mode.

- Changed the date format so it no longer displays as "Day 1", "Day 2".
- The date format now follows the convention "Saturday, March 23, 2024"
- Dates are able to dynamically be added using the "add another day" button, with the consequent day still following the same convention.
- Installed a new package through the use of npm (date-fns) in order to have these date formats be universally usable through the website.
- Reformatted the Activity.jsx file from TypeScript to JavaScript.
- Activity.jsx is now Activity.js.
- Fixed a bug which occurred on the itinerary page where activities displayed as a solid color specifically in dark mode.

Fixes #46
Fixes #47

# Add an image of the change (if applicable)
image

# Type of change

- [X] Bug fix 
- [X] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by amai83 — APPROVED** [review]
Formatting of dates were changed to be more concise and clear to users. Functionality remains the same, users are able to adjust the order of their activities to their liking. I submitted issue #53 concerning the calendar. Users are able to create an itinerary with past dates. Other than that, approving new changes to merge with master.

**Review by VyProductions — CHANGES_REQUESTED** [review]
I don't believe this pull request should have the issue templates included, nor the `package-lock.json` and `package.json` files. If you're able to get rid of the changes to the following files by altering your commit history, then please do so:
```
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation-needed.md
.github/ISSUE_TEMPLATE/feature-development-enhancement.md
frontend/package-lock.json
frontend/package.json
```

**Comment by FPSwitch** [comment]
I would approve the change but also have a suggestion. As of now, it shows the full day (Monday, Tuesday, etc.). I think for simplicity, we could abbreviate each day (Mon. Tues. Wed. Thurs. Fri. etc.) as this can help simplify and take up less characters.

**Review by printer99 — CHANGES_REQUESTED** [review]
The changes look good, but I think we could probably change the color scheme a bit. I love dark themes in apps, but this one might be a bit too dark. We also do not have a set theme for the webpage yet. As William said you should remove the excess files from your pull request. Other than that this looks like a pull request to me!

The files being:
```
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation-needed.md
.github/ISSUE_TEMPLATE/feature-development-enhancement.md
frontend/package-lock.json
frontend/package.json```

**Review by tylereg03 — COMMENTED** [review]
Deleted the files from my pr:
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation-needed.md
.github/ISSUE_TEMPLATE/feature-development-enhancement.md
frontend/package-lock.json
frontend/package.json

**Review by axelauda — APPROVED** [review]
Looks like you removed the conflicting files from your pull request. Now it should merge with no problem. Also great job fixing the display bug with the activity components, they look a lot better now. Approved!!

**Review by printer99 — APPROVED** [review]
Everything looks good to me now!

**Review by VyProductions — APPROVED** [review]
The extraneous files have been removed from the PR. Looks good to me now. Thank you.

**Pull request merged**
