### PR TITLE
Updated MapPage to look a bit better

### PR DESCRIPTION
**Pull request by printer99**
---
name: "Reworked Map Page"
about: "Map Page has an image and map linked to the image, along with a map marker to that location"
title: "feat: Interaction with images and the map "
labels: "feature-request, not-reviewed"
assignees: ""
---

# Description

There is now an outline of where certain components of the map page will go and how they will function. The map appears when the image is clicked (Currently only works for 1 image).

Fixes # (issue)

# Add an image of the change (if applicable)

# Type of change

- [ ] Bug fix 
- [x] New feature 
- [x] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by esquek1 — APPROVED** [review]
This looks like a great first pull request for the Map page. I did notice that the map slightly covers the photos. Maybe in the next pull request, when a photo is clicked, a window pops up or simply just moving it more down. This can be discuss in the next meeting. Great job.

Screenshot from 2024-03-25 14-34-22

**Review by VyProductions — CHANGES_REQUESTED** [review]
Tested the page on my end. It looks great, however it doesn't look like you've considered the dark mode modifications to the components on the page.

Another thing I notice is that the map which opens up on-click could likely use some padding between itself and the surrounding components. At the moment it's directly adjacent to the images above it.

Additionally, zooming in/out might need to be reviewed here for scaling. The map maintains the same aspect ratio during zooming, and zooming in causes the pictures to get out of sync with each other as far as their size goes.

I'd request that these issues be addressed or otherwise considered for future implementation.

**Comment by printer99** [comment]
@VyProductions @esquek1 The issues mentioned will be fixed in a future pull request! This was meant to show the rough idea of how the overall layout would look. I haven't quite settle on which locations to display for trip spots or fine-tuned the CSS.

**Review by renm10 — APPROVED** [review]
Your commit to your map page looks like a huge addition to the map page! I like how you can click on each continent and it'll automatically bring you there. 
Everything looks fine so far, however I do want to address just in case that clicking Antartica isn't implemented yet. 
For future implementations in the map page, the search bar should be fixed as its extending further than the nav bar.

**Comment by printer99** [comment]
Ah yes, due to poor reception Antarctica is being removed because no one likes going there :(. It seems I accidentally left it at the bottom and will delete it in the next PR.

**Pull request merged**
