### PR TITLE
Added error checking for a valid date range.

### LINKED ISSUE #22: Start date and end date error check required on Itinerary page
Currently, when the user enters a end date EARLIER than the start date, the start button can still be clicked. We will need error checking for a valid start and end date before the user can proceed further.
Required Error Checks:
- Check if user entered a end date later than the start date. (If not let the user know)

### PR DESCRIPTION
**Pull request by renm10**
Added simple error checking for a valid date range.
Example:
Start Date @ 3/6  End Date @ 3/5  is INVALID
Start Date @ 3/4  End Date @ 3/4  is VALID
Start Date @ 3/4  End Date @ 3/6  is VALID

The start button is disabled until the user enters a valid date range.
This fixes the bug reported by the issue #22.
Closes #22.

### CODE REVIEW

**Review by amai83 — COMMENTED** [review]
Tested the error checking of date selection, and it works without any problem. That is working well, but I don't think there is enough changes for this to be a sufficient pull request. I would approve it, but let's see what the others think as well.

**Review by Niblick1020 — APPROVED** [review]
Pretty small Pull request. Looks good on my end!

**Review by printer99 — APPROVED** [review]
Small pull request. The problem mentioned does appear to be fixed. Everything looks good to me.

**Review by VyProductions — COMMENTED** [review]
I also believe this is too small to be a pull request by itself. I would recommend combining this with other changes before it would be significant enough to merge.

**Pull request closed without merging**
