### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by Ramirez-Christopher**
acknowledging issue #41, A template for whenever someone does a pull request. Please let me know if there's any change you'd like to see.

### CODE REVIEW

**Review by printer99 — APPROVED** [review]
Looks good to me! I don't know if we want to have a guideline for how we title the PR as well.

**Review by jenlcmc — APPROVED** [review]
Look good but I think we can also add like pics or images section so that we can show or have visual example of what the work look like

**Comment by Ramirez-Christopher** [comment]
> Looks good to me! I don't know if we want to have a guideline for how we title the PR as well.

Thank you, I've added a title template.

**Comment by Ramirez-Christopher** [comment]
> Look good but I think we can also add like pics or images section so that we can show or have visual example of what the work look like

Thank you, I've added an image section.

**Review by tylereg03 — APPROVED** [review]
Everything looks great! This should make our PRs neater, and give each of us a better idea of what our pushes are providing. Approved!

**Pull request merged**
