### PR TITLE
Cleaning ItineraryPage.js File

### PR DESCRIPTION
**Pull request by renm10**
Cleaned up ItineraryPage.js file that contained multiple components into several files.
Also it contained a small error where it had a component and a function with the same name ItineraryAccordion.js so I deleted the function to fix redundancy.

### CODE REVIEW

**Comment by tylereg03** [comment]
Everything is looking good. Changes clean up the itinerary page, making it more readable and concise. Great refactor, approved!

**Comment by Jordan-Scherf** [comment]
Great Job, The refactor looks nice and it did clean up the clutter page. Using and understanding the page is a bit easier now. Great job. I believe we might add more components to this in the future, but it is a great working point for now.

**Review by Jordan-Scherf — APPROVED** [review]
Great Job, The refactor looks nice and it did clean up the clutter page. Using and understanding the page is a bit easier now. Great job. I believe we might add more components to this in the future, but it is a great working point for now.

**Review by tylereg03 — APPROVED** [review]
Everything is looking good. Changes clean up the itinerary page, making it more readable and concise. Great refactor, approved!

**Review by Ramirez-Christopher — APPROVED** [review]
Great job refactoring. The changes look great. Let's talk about how we may interact other components with the itinerary page in the future!

**Pull request merged**
